# Generated by Django 3.1 on 2020-09-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='upload',
            new_name='Mp3',
        ),
    ]
