# Generated by Django 3.1 on 2020-09-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0003_auto_20200920_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='email',
            field=models.EmailField(default='your email', max_length=254),
        ),
        migrations.AddField(
            model_name='music',
            name='song_title',
            field=models.CharField(default='song title', max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='Mp3',
            field=models.FileField(help_text='Upload mp3 Format', upload_to='fans_files/mp3/'),
        ),
    ]
